apiVersion: v1
kind: Service
metadata:
  name: crub-dynamo-db-service
spec:
  selector:
    app: crud-dynamo-db
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
